### ISSUE TITLE
License

### ISSUE THREAD

**Issue by legba7** [OPEN-NEXT/WP2.3-Guideline-and-template-for-documentation-of-OSH-design-reuse#1]
The license CC-BY-SA 4.0 mentioned in the README.md introduction contradicts the file LICENSE in that the GPL v3.0 is specified. 
I recommend replacing the license with a permissive license such as MIT License https://choosealicense.com/licenses/mit/ .

**Comment by penyuan** [comment]
This repository contains documentation guidelines and templates, not code, so software licenses such as the GPLv3 or MIT are not appropriate.

In this case, the CC BY-SA 4.0 license indicated in the README would work. I think a better step would be to replace the contents of the LICENSE file with CC BY-SA 4.0.

**Comment by legba7** [comment]
Indeed, no software here. MIT License is not applicable.
I think the use of a reciprocal license can inhibit the adoption of the template. 
Like reciprocal licenses can inhibit the adoption of libraries.
If License CC BY-SA 4.0 is used then the attribution should be in the documentation and the attribution and the license should be marked as mandatory.
I think a more permissive license like (CC0, CC-BY, <https://creativecommons.org/about/cclicenses/>) would fit better to a template. For example, CC BY-SA 4.0 is compatible with CERN-OHL but not with TAPR-OHL.

**Comment by rpinquie** [comment]
Thanks guys for your feedback. We've updated the repository with a single permissive CC-BY license.

**Comment by rpinquie** [comment]
Thanks for your feedback, we have replaced it with a single permissive CC-BY license.
